# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170417_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='posts',
            new_name='post',
        ),
    ]
