# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170417_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='data',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
        ),
    ]
